FROM python:3.8
RUN mkdir /usr/src/challenge-01/
COPY . /usr/src/challenge-01/
WORKDIR /usr/src/challenge-01/
ENV PORT 5000
ENV FLASK_DEBUG 1
COPY requirements.txt ./
EXPOSE 5000
RUN pip install --no-cache-dir -r requirements.txt
CMD [ "python", "./setup.py", "./app.py" ]