FROM python:3.9
RUN mkdir /usr/src/challenge-01 && chmod 777 /usr/src/challenge-01
COPY ./ /usr/src/challenge-01
WORKDIR /usr/src/challenge-01
COPY requirements.txt ./
EXPOSE 5000
RUN pip install -r requirements.txt
CMD [ "python", "./src/app.py"]