version: '3'
services:
  web:
    build:  ./challenge-01/
    volumes: 
        - ./challenge-01/:/usr/src/challenge-01/
    ports:
      - "5000:5000"
    environment: 
        PORT: 5000
        FLASK_DEBUG: 1